name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PROJECT_ID: lengolf-operations
  REGION: asia-southeast1
  SERVICE: lengolf-sales

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker push
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build \
          --build-arg APP_LOGIN='${{ secrets.APP_LOGIN }}' \
          --build-arg APP_PASSWORD='${{ secrets.APP_PASSWORD }}' \
          --build-arg GOOGLE_KEY='${{ secrets.GOOGLE_KEY }}' \
          -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}" \
          .

    - name: Push Docker image
      run: docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}"

    - name: Deploy to Cloud Run
      run: |
        gcloud run jobs create ${{ env.SERVICE }} \
          --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}" \
          --region ${{ env.REGION }} \
          --max-retries 3 \
          --task-timeout "3600s" \
          --set-env-vars "APP_LOGIN=${{ secrets.APP_LOGIN }},APP_PASSWORD=${{ secrets.APP_PASSWORD }},GOOGLE_KEY=${{ secrets.GOOGLE_KEY }}" || \
        gcloud run jobs update ${{ env.SERVICE }} \
          --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}" \
          --region ${{ env.REGION }} \
          --max-retries 3 \
          --task-timeout "3600s" \
          --set-env-vars "APP_LOGIN=${{ secrets.APP_LOGIN }},APP_PASSWORD=${{ secrets.APP_PASSWORD }},GOOGLE_KEY=${{ secrets.GOOGLE_KEY }}"

    - name: Set up Cloud Scheduler
      run: |
        gcloud scheduler jobs create http ${{ env.SERVICE }}-scheduler \
          --location ${{ env.REGION }} \
          --schedule "0 10-23 * * *" \
          --http-method POST \
          --uri "https://${{ env.REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${{ env.PROJECT_ID }}/jobs/${{ env.SERVICE }}:run" \
          --oauth-service-account-email "${{ secrets.WIF_SERVICE_ACCOUNT }}" || \
        gcloud scheduler jobs update http ${{ env.SERVICE }}-scheduler \
          --location ${{ env.REGION }} \
          --schedule "0 10-23 * * *" \
          --http-method POST \
          --uri "https://${{ env.REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${{ env.PROJECT_ID }}/jobs/${{ env.SERVICE }}:run" \
          --oauth-service-account-email "${{ secrets.WIF_SERVICE_ACCOUNT }}" 